In [17]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.cluster as cluster
from sklearn import datasets
from sklearn.decomposition import PCA
from sklearn.decomposition import FastICA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import time
%matplotlib inline

sns.set_context('poster')
sns.set_color_codes()
plot_kwds = {'alpha' : 0.25, 's' : 80, 'linewidths':0}

## 1. PCA

In [9]:
data_wine = datasets.load_wine()

X = data_wine.data
y = data_wine.target
target_names = data_wine.target_names

pca = PCA(n_components=5)
X_pca = pca.fit(X).transform(X)
print (pca.explained_variance_ratio_)
print ("sum : %s" % str(sum(pca.explained_variance_ratio_))  )

[  9.98091230e-01   1.73591562e-03   9.49589576e-05   5.02173562e-05
   1.23636847e-05]
sum : 0.999984686115


In [11]:
pca = PCA(n_components=1)
X_pca = pca.fit(X).transform(X)
print (pca.explained_variance_ratio_)
print ("sum : %s" % str(sum(pca.explained_variance_ratio_))  )

[ 0.99809123]
sum : 0.998091230492


## 2. FastICA

In [20]:

num_classes = len(target_names)
ica = FastICA(n_components=num_classes)

X_ica = ica.fit(X).transform(X)

In [21]:
print (X_ica)

[[-0.00334972  0.11910486  0.11213869]
 [-0.15765118  0.03249771  0.09016793]
 [ 0.00914578 -0.07218324  0.08818214]
 [ 0.02650928 -0.05628773  0.16508611]
 [ 0.06373482  0.08368533  0.01792269]
 [-0.014961   -0.03564201  0.16496531]
 [-0.07854424 -0.07566622  0.11656963]
 [ 0.03617976  0.02075661  0.14029138]
 [-0.10300465 -0.01428671  0.07383816]
 [-0.05053655 -0.03553967  0.06593565]
 [ 0.02339881 -0.11039645  0.15758177]
 [-0.03829988 -0.10148383  0.10537909]
 [-0.06201064 -0.13369731  0.10723107]
 [-0.16256595 -0.03878384  0.09531168]
 [-0.0919159  -0.07482603  0.18102837]
 [ 0.02236816 -0.03121996  0.1300716 ]
 [ 0.08780574 -0.01007248  0.1260369 ]
 [ 0.06957635 -0.00619121  0.09062057]
 [ 0.02582875 -0.12187052  0.19644578]
 [-0.0459741   0.1099585   0.05666659]
 [-0.01359986  0.16724356  0.05526656]
 [-0.01356399  0.0174048   0.01108621]
 [-0.05233246 -0.01411073  0.06948464]
 [-0.04072163 -0.05465663  0.05280216]
 [-0.00636224 -0.03719641  0.01421181]
 [ 0.15622813  0.0564406 

## 3. LDA

In [22]:
lda = LinearDiscriminantAnalysis(n_components=num_classes)
X_lda = lda.fit(X, y).transform(X)